#ifndef _FWPROTOCOL_C
#define _FWPROTOCOL_C

#include "types.h"
#include "fwprotocol.h"

/*
 * This file is autogenerated.
 * Changes made to this file can be overwritten.
 */

#if defined(__cplusplus)
extern "C"
{
#endif

/* @@GENERATED_CODE@@ */

#if defined(__cplusplus)
};
#endif

#endif // _FWPROTOCOL_C

// vim: ts=4 shiftwidth=4
